name: Signum Design Documents Version Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from the branch
        uses: actions/checkout@v4
      
      - name: Run release please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_TOKEN }}
          changelog-path: changelog.md
          update-changelog: true
